#! /bin/bash
function ip () {
    echo "`ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`"
}

var=`ip`
routervar="${var%.*}.255"
times=${1:-15}
ping -c $times $routervar
echo -e "\nDevices on this network:\n"
arp -a
